# Default values for kbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "mardukay/kbot"
  tag: "v1.0.6-3d61774"
  os: "linux"
  arch: "amd64"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
